// ============ REDUX GLOBAL ACTION TYPE =============
export const GLOBAL_TYPES = {
  ALERT: "ALERT",
  LOADING: "LOADING",
  SOCKET: "SOCKET",
  REFRESH_TOKEN_LOADING: "REFRESH_TOKEN_LOADING",
  ONLINE_USER: "ONLINE_USER",
  OFFLINE_USER: "OFFLINE_USER"
}