export const landingPageLayoutUrls: string[] = [
  '/',
  '/jobs',
  '/contact-us',
  '/login',
  '/login-request',
  '/recover',
  '/change-password',
  '/privacy-policy',
  '/terms-conditions',
  '/internship',
  '/apply',
];

export const dgteamDynamicInfo = [
  { title: 'Home', url: '/' },
  { title: 'Jobs', url: '/jobs' },
  { title: 'Contact Us', url: '/contact-us' },
  { title: 'Login', url: '/login' },
  { title: 'Recover', url: '/recover' },
  { title: 'Change Password', url: '/change-password' },
  { title: 'Privacy Policy', url: '/privacy-policy' },
  { title: 'Terms & Conditions', url: '/terms-conditions' },
  { title: 'Internship', url: '/internship' },
  { title: 'Apply', url: '/apply' },
  { title: 'Dashboard', url: '/dashboard' },
  { title: 'Profile', url: '/dashboard/profile' },
  { title: 'Task', url: '/dashboard/tasks' },
  { title: 'Salary', url: '/dashboard/salary' },
  { title: 'Team', url: '/dashboard/team' },
  { title: 'Event', url: '/dashboard/event' },
  { title: 'Timeoff', url: '/dashboard/timeoff' },
  { title: 'Rewards', url: '/dashboard/rewards' },
  { title: 'Benefits', url: '/dashboard/benefits' },
  { title: 'Add User', url: '/dashboard/add-user' },
  { title: 'Requests', url: '/dashboard/requests' },
  { title: 'Add Benefits', url: '/dashboard/add-benefits' },
  { title: 'Users', url: '/dashboard/users' },
  { title: 'Users', url: '/dashboard/users/archived' },
  { title: 'User Profile', url: `/dashboard/user/[id]` },
  { title: 'Contact', url: `/dashboard/contact` },
  { title: 'Settings', url: `/dashboard/settings` },
  { title: 'Notifications', url: `/dashboard/notifications` },
  { title: 'Job', url: `/dashboard/job` },
];
